### ISSUE TITLE
Out of scope variable

### ISSUE THREAD

**Issue by juuuuuuuj** [sancarn/copy-to-clipboard#1]
Hi,

`const text` is out of scope for the success condition at the end. Therefore, `window.close()` is never run. You should add the setTimeout function inside the `try` block or changing `const` to `var` to expand scope.

Regards.

**Comment by sancarn** [comment]
Makes sense, should be fixed now :)

**Comment by jakesprofile** [comment]
I think I'm doing something wrong. I did the following...

1. Put the code in a notepad and saved as an ASPX file.
2. I uploaded the ASPX file to a OneDrive folder.
3. I linked the file in the JSON code for the SharePoint list column formatting using the copy icon to deploy the link from OneDrive.
4. The link successfully opens the tab and copies what I need to the clipboard with no issue; it just doesn't auto-close the tab. 

This workaround you provided is amazing, and I truly appreciate the work you did. I just don't know why it won't close for me. Any thoughts? I feel like I'm doing something wrong.

**Comment by sancarn** [comment]
@jakesprofile Unfortunately not sure, maybe has something to do with the aspx format... typically tabs don't just auto-close, for security reasons. Could also be due to the way you're opening links in a new tab. Other than that, I can't really say, sorry!

**Comment by jakesprofile** [comment]
@sancarn, no worries. I thought I'd pick your brain to see if you had any ideas. I'm really a noob when it comes to coding, especially JavaScript. I'm just happy I got it to work as far as I did. Thanks again, solid workaround. 😊
